#!/bin/bash

directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [[ -f "${directory}/.vimrc" ]]; then
    cp ${directory}/.vimrc ~/.vimrc
fi

if [[ -f "${directory}/.pretty_prompt" ]]; then
    cp ${directory}/.pretty_prompt ~/.pretty_prompt

    cp ~/.bashrc ~/.bashrc.bk
    echo "#--------------------------------------------------------------------------------------#" >> ~/.bashrc
    echo "# Auto generated by install_dotfile.sh                                                 #" >> ~/.bashrc
    echo "#--------------------------------------------------------------------------------------#" >> ~/.bashrc
    echo "if [[ -f ~/.pretty_prompt ]]; then \n\t. ~/.pretty_prompt\nfi" >> ~/.bashrc
    echo "" >> ~/.bashrc
fi
