#!/bin/bash

this_directory="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
dotfiles_directory=${this_directory}/dotfiles

if [[ -f "${dotfiles_directory}/.vimrc" ]]; then
    cp ${dotfiles_directory}/.vimrc ~/.vimrc
fi

if [[ -f "${dotfiles_directory}/.pretty_prompt" ]]; then
    cp ${dotfiles_directory}/.pretty_prompt ~/.pretty_prompt

    cp ~/.bashrc ~/.bashrc.bk
    echo "#--------------------------------------------------------------------------------------#" >> ~/.bashrc
    echo "# Auto generated by install_dotfile.sh                                                 #" >> ~/.bashrc
    echo "#--------------------------------------------------------------------------------------#" >> ~/.bashrc
    echo "if [[ -f ~/.pretty_prompt ]]; then \n\t. ~/.pretty_prompt\nfi" >> ~/.bashrc
    echo "" >> ~/.bashrc
fi
