services:
  qmk:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${QMK_HOME:-${HOME}/src/qmk_firmware}:/workspace
      - ./bin:/qmk_bin
    working_dir: /workspace
    environment:
      # Required
      - KEYBOARD=${KEYBOARD:-crkbd/rev1}
      - KEYMAP=${KEYMAP:-default}
      # Optional
      # See https://docs.qmk.fm/feature_converters#converters
      - CONVERT_TO=promicro_rp2040
