services:
  qmk:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${QMK_HOME:-${HOME}/src/qmk_firmware}:/workspace
      - ./bin:/qmk_bin
    working_dir: /workspace
    environment:
      - KEYBOARD=${KEYBOARD}
      - KEYMAP=${KEYMAP}
      - CONVERT_TO=${CONVERT_TO}
