gui:
  theme:
    activeBorderColor:
      - "#d69f73"
      - bold
    inactiveBorderColor:
      - "#82937f"
    optionsTextColor:
      - "#adcbe0"
    selectedLineBgColor:
      - "#22332b"
    selectedRangeBgColor:
      - "#22332b"
    cherryPickedCommitBgColor:
      - "#22332b"
    cherryPickedCommitFgColor:
      - "#c8dfb8"
    unstagedChangesColor:
      - "#cc9488"
    defaultFgColor:
      - "#e8e3d5"
    searchingActiveBorderColor:
      - "#d8c39a"
      - bold
git:
  commit:
    signOff: true
