-- Author: Michael Mead
require('mmead.global')
require('mmead.lazy')
require('mmead.theme')
require('mmead.telescope')
require('mmead.lsp')
require('mmead.treesitter')
require('mmead.filebrowser')
require('mmead.git')
require('mmead.dap')
require('mmead.copilot')
require('mmead.cmake')
require('mmead.python')
