vim.o.wrap = false
vim.o.number = true
vim.o.relativenumber = true
vim.o.wildmenu = true
vim.o.errorbells = false
vim.o.splitright = true
vim.o.splitbelow = true
vim.o.startofline = false
vim.o.backspace = "indent,eol,start"
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.incsearch = true
vim.o.wildignore = ".pyc,.swp,*/.git/*,*/.DS_Store,*/build/*,*/tmp/*,*/venv/*"
vim.o.wildmode = "longest:full,full"
vim.o.swapfile = false
vim.o.timeout = true
vim.o.timeoutlen = 500
vim.o.ttimeoutlen = 100
vim.o.signcolumn = "yes"
vim.o.mouse = "a"
vim.o.scrolloff = 8
vim.o.cursorline = true
vim.o.hlsearch = false
vim.o.termguicolors = true
vim.o.pumheight = 8
vim.o.laststatus = 3
vim.o.spelllang = "en_us"
vim.o.spelloptions = "camel"
vim.o.spell = false -- enabled by filetype

-- Netrw
vim.g.netrw_keepdir = 0
