set -g mouse on

# set -g default-terminal "xterm-256color"
# set-option -ga terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "tmux-256color"

# Use system clipboard
set -g set-clipboard on

# Escape fast
set -g escape-time 0

# Vim style
set -g mode-keys vi
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

# Status bar styling
set -g status-position top
set -g status-justify left
set -g status-style 'fg=colour8 bg=colour0'
set -g status-right-length 100
set -g status-left-length 100
set -g status-left '#[fg=colour0,bg=colour4,bold] #S #[fg=colour4,bg=colour0,nobold]'
set -g status-right ''

# Window status styling
setw -g window-status-style 'fg=colour8 bg=colour0'
setw -g window-status-format ' #I #[fg=colour8]#W #[fg=colour8]#F '
setw -g window-status-current-style 'fg=colour7 bg=colour0 bold'
setw -g window-status-current-format ' #I #[fg=colour7]#W #[fg=colour8]#F '
setw -g window-status-bell-style 'fg=colour0 bg=colour3 bold'

# Pane borders
set -g pane-border-style 'fg=colour8'
set -g pane-active-border-style 'fg=colour4'

# Pane switching
bind -r C-h select-pane -L
bind -r C-j select-pane -D
bind -r C-k select-pane -U
bind -r C-l select-pane -R

# Pane resizing
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# Reload
bind r source-file ~/.tmux.conf

# Test splits
bind T split-window -h -f -l 15 -c "#{pane_current_path}"
bind t split-window -v -f -l 15 -c "#{pane_current_path}"

# Git
bind g popup -E -w 100% -h 100% -d "#{pane_current_path}" "lazygit"
bind w popup -E -w 100% -h 100% -d "#{pane_current_path}" "fzf-tmux-session"

# Shell
bind a popup -E -w 80% -h 40% -d "#{pane_current_path}" "/bin/zsh"
